name: Tailscale Exit Node
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Clear all Clients on tailscale
      run: |
        SCRIPT_URL="https://raw.githubusercontent.com/Official-Aleks-Bot/TAILscale/master/deleteEmptyServers.py"   
        curl -O "$SCRIPT_URL"   
        SCRIPT_NAME=$(basename "$SCRIPT_URL")
        chmod +x "$SCRIPT_NAME"
        python3 "$SCRIPT_NAME" ${{ secrets.TSKEY }} ${{ secrets.TAILNET }}
      env:
        TSKEY: ${{ secrets.TSKEY }}
        TAILNET: ${{ secrets.TAILNET }}

    - name: Modify Firewall
      run: |
        echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
        sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
        echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf
        echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.conf
        sudo sysctl -p /etc/sysctl.conf
        
    - name: Install Tailscale
      run: |
        sudo curl -fsSL https://tailscale.com/install.sh -o install_tailscale.sh
        sudo sh install_tailscale.sh
        
    - name: Set Tailscale Hostname and Advertise Exit Node
      run: |
        sudo tailscale up --authkey=${{ secrets.APIKEY }} --advertise-exit-node
      env:
        APIKEY: ${{ secrets.APIKEY }}
        
    - name: Download and run Python script
      run: |
        SCRIPT_URL="https://raw.githubusercontent.com/Official-Aleks-Bot/TAILscale/master/main.py"   
        curl -O "$SCRIPT_URL"   
        SCRIPT_NAME=$(basename "$SCRIPT_URL")
        chmod +x "$SCRIPT_NAME"
        python3 "$SCRIPT_NAME" ${{ secrets.TSKEY }} ${{ secrets.TAILNET }}
      env:
        TSKEY: ${{ secrets.TSKEY }}
        TAILNET: ${{ secrets.TAILNET }}
        
    - name: Wait 5 hours
      run: sleep 21300  # 5 hours in seconds

    - name: Curl
      run: ${{ secrets.Curl }}
      env:
        APIKEY: ${{ secrets.Curl }}
        
    - name: Kill tailscale
      run: sudo service tailscaled stop
