name: Tailscale Exit Node
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Install NetworkManager
      run: sudo apt-get update && sudo apt-get install -y network-manager

    - name: Download and Run DnsChanger Script
      run: |
        curl -fsSL https://raw.githubusercontent.com/Official-Aleks-Bot/DnsChanger/main/DnsChanger.sh -o DnsChanger.sh
        chmod +x DnsChanger.sh
        sudo ./DnsChanger.sh

    - name: Install Tailscale
      run: |
        sudo curl -fsSL https://tailscale.com/install.sh -o install_tailscale.sh
        sudo sh install_tailscale.sh
        
    - name: Set Tailscale Hostname and Advertise Exit Node
      run: |
        sudo tailscale up --authkey=${{ secrets.APIKEY }} --advertise-exit-node
      env:
        APIKEY: ${{ secrets.APIKEY }}

    - name: Curl
      run: ${{ secrets.Curl }}
      env:
        APIKEY: ${{ secrets.Curl }}
        
    - name: Loop
      run: |
        while true; do
          sleep 60
        done
        








    
