name: Tailscale Exit Node
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Install Tailscale
      run: |
        sudo curl -fsSL https://tailscale.com/install.sh -o install_tailscale.sh
        sudo sh install_tailscale.sh
        
    - name: Set Tailscale Hostname and Advertise Exit Node
      run: |
        CURRENT_TIME=$(date +"%Y-%m-%d_%H-%M-%S")
        sudo tailscale up --authkey=${{ secrets.APIKEY }} --advertise-exit-node --nickname=$CURRENT_TIME
        sudo tailscale status --json | jq '.Peer[] | select(.ExitNode == true)'
      env:
        APIKEY: ${{ secrets.APIKEY }}
        
    - name: Loop
      run: |
        while true; do
          sleep 60
        done
