name: FreeRDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Run Tailscale
      run: curl -fsSL https://tailscale.com/install.sh | sh -s -- --auth-key=$APIKEY --advertise-exit-node

    - name: loop
      run: |
        while true; do
          sleep 60
        done
